# Generated by Django 4.1.6 on 2023-03-12 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quarter', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Квартал')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Квартал',
                'verbose_name_plural': 'Кварталы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID Пользователя Телеграм')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия пользователя')),
                ('access', models.CharField(max_length=100, verbose_name='Доступ')),
                ('role', models.CharField(max_length=100, verbose_name='Роль в секторе')),
                ('status', models.CharField(max_length=100, verbose_name='Статус')),
                ('photo', models.ImageField(blank=True, upload_to='photo/')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=200, null=True, verbose_name='Активность')),
                ('comment', models.CharField(max_length=200, null=True, verbose_name='Комментарий')),
                ('criterion', models.CharField(max_length=200, null=True, verbose_name='Критерий')),
                ('employee', models.ForeignKey(on_delete=models.SET(0), related_name='mistake_employee', to='db_api.user', verbose_name='Сотрудник')),
                ('initiator', models.ForeignKey(on_delete=models.SET(0), related_name='mistake_initiator', to='db_api.user', verbose_name='Инициатор')),
                ('quarter', models.ForeignKey(on_delete=models.SET(0), related_name='like_employee', to='db_api.quarter', verbose_name='')),
            ],
            options={
                'verbose_name': 'Ошибка',
                'verbose_name_plural': 'Ошибки',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=models.SET(0), related_name='like_employee', to='db_api.user', verbose_name='Сотрудник')),
                ('initiator', models.ForeignKey(on_delete=models.SET(0), related_name='like_initiator', to='db_api.user', verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=200, null=True, verbose_name='Активность')),
                ('comment', models.CharField(max_length=200, null=True, verbose_name='Комментарий')),
                ('criterion', models.CharField(max_length=200, null=True, verbose_name='Критерий')),
                ('employee', models.ForeignKey(on_delete=models.SET(0), related_name='bonus_employee', to='db_api.user', verbose_name='Сотрудник')),
                ('initiator', models.ForeignKey(on_delete=models.SET(0), related_name='bonus_initiator', to='db_api.user', verbose_name='Инициатор')),
                ('quarter', models.ForeignKey(on_delete=models.SET(0), related_name='quarter', to='db_api.user', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Бонус',
                'verbose_name_plural': 'Бонусы',
            },
        ),
    ]
