# Generated by Django 4.1.6 on 2023-03-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='quarter',
            field=models.ForeignKey(on_delete=models.SET(0), related_name='bonus_quarter', to='db_api.quarter', verbose_name='Квартал'),
        ),
    ]
