# Generated by Django 4.1.6 on 2023-03-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0002_alter_bonus_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='quarter',
            field=models.ForeignKey(default=1, on_delete=models.SET(0), related_name='like_quarter', to='db_api.quarter', verbose_name='Квартал'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mistake',
            name='quarter',
            field=models.ForeignKey(on_delete=models.SET(0), related_name='mistake_quarter', to='db_api.quarter', verbose_name='Квартал'),
        ),
    ]
