# Generated by Django 4.1.6 on 2023-03-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0003_like_quarter_alter_mistake_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sop',
            field=models.CharField(choices=[('СТПВ', 'Ставрополь'), ('Омск', 'Омск'), ('ВЛГ', 'Волгоград'), ('СМР', 'Самара')], default=1, max_length=100, verbose_name='СОП'),
            preserve_default=False,
        ),
    ]
